service:
  name: image-resizer

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-domain-manager
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs10.x
  profile: personal-sandbox # ChangeIt
  region: ap-south-1 # ChangeIt
  stage: ${opt:stage, 'dev'}

custom:
  env: ${file(./env/${self:provider.stage}.yml)} # ChangeIt
  subDomain: ${self:custom.env.SUBDOMAIN}
  host: ${self:custom.env.DOMAIN}.${self:custom.env.ROOT_DOMAIN}
  customDomain:
    domainName: ${self:custom.subDomain}.${self:custom.host}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional' # ChangeIt
  webpack:
    packager: npm
    includeModules:
      forceExclude:
        - aws-sdk

functions: # add your functions
  health:
    handler: src/health.health
    name: ${self:service.name}-${self:provider.stage}-health
    descptions: default end point used to return the status of health
    events:
      - http:
          method: get
          path: health
  resizeHandler:
    handler: src/resizeHandler.resizeHandler
    name: ${self:service.name}-${self:provider.stage}-resizeHandler
    description: will get triggered when a jpeg image is uploaded or renamed in uploads floder.
    environment:
      UPLOADS_FOLDER: 'uploads/'
      THUMBNAILS_FOLDER: 'thumbnails/'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "S3:ListBucket"
          - "S3:GetObject"
          - "S3:PutObject"
        Resource: arn:aws:s3:::thumbnails-xpparel/*
    events:
      - s3:
          bucket: thumbnails-xpparel
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpeg
  thumbnailsDetails:
    handler: src/thumbnailsDetails.thumbnailsDetails
    name: ${self:service.name}-${self:provider.stage}-thumbnailsDetails
    description: will get triggered when a jpeg image is uploaded or renamed in uploads floder.
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "S3:ListBucket"
          - "S3:GetObject"
          - "S3:PutObject"
        Resource: arn:aws:s3:::thumbnails-xpparel/thumbnaisl/*
    events:
      - s3:
          bucket: thumbnails-xpparel
          event: s3:ObjectCreated:*
          rules:
            - prefix: thumbnails/
            - suffix: .jpeg

resources:
  # Output
  - ${file(InfrastructureResources/outputs.yml)}
