service:
  name: image-resizer

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-domain-manager
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs10.x
  profile: personal-sandbox # ChangeIt
  region: ap-south-1 # ChangeIt
  stage: ${opt:stage, 'dev'}

custom:
  env: ${file(./env/${self:provider.stage}.yml)} # ChangeIt
  subDomain: ${self:custom.env.SUBDOMAIN}
  host: ${self:custom.env.DOMAIN}.${self:custom.env.ROOT_DOMAIN}
  customDomain:
    domainName: ${self:custom.subDomain}.${self:custom.host}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional' # ChangeIt
  webpack:
    packager: npm
    includeModules:
      forceExclude:
        - aws-sdk

functions: # add your functions
  health:
    handler: src/health.health
    events:
      - http:
          method: get
          path: health
  resizeHandler:
    handler: src/resizeHandler.resizeHandler
    events:
      - s3:
          bucket: image-resizer-xpparel
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpeg

resources:
  # Output
  - ${file(InfrastructureResources/outputs.yml)}
